# Diabetic

In [285]:
import warnings
warnings.filterwarnings("ignore")

In [286]:
import pandas as pd
import numpy as np
from scipy.io.arff import loadarff 
from io import StringIO, BytesIO
import urllib.request

In [287]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/00329/messidor_features.arff'
# raw_data = loadarff(url)
# df_data = pd.DataFrame(raw_data[0])
resp = urllib.request.urlopen(url)
data, meta = loadarff(StringIO(resp.read().decode('utf-8')))

In [288]:
col_names = []
for i in range(20):
  if i == 0:
      col_names.append('quality')
  if i == 1:
      col_names.append('prescreen')
  if i >= 2 and i <= 7:
      col_names.append('ma' + str(i))
  if i >= 8 and i <= 15:
      col_names.append('exudate' + str(i))
  if i == 16:
      col_names.append('euDist')
  if i == 17:
      col_names.append('diameter')
  if i == 18:
      col_names.append('amfm_class')
  if i == 19:
      col_names.append('label')

In [289]:
df = pd.DataFrame(data)
df.columns = [col_names]
df

quality prescreen   ma2   ma3   ma4   ma5   ma6   ma7   exudate8  \
0        1.0       1.0  22.0  22.0  22.0  19.0  18.0  14.0  49.895756   
1        1.0       1.0  24.0  24.0  22.0  18.0  16.0  13.0  57.709936   
2        1.0       1.0  62.0  60.0  59.0  54.0  47.0  33.0  55.831441   
3        1.0       1.0  55.0  53.0  53.0  50.0  43.0  31.0  40.467228   
4        1.0       1.0  44.0  44.0  44.0  41.0  39.0  27.0  18.026254   
...      ...       ...   ...   ...   ...   ...   ...   ...        ...   
1146     1.0       1.0  34.0  34.0  34.0  33.0  31.0  24.0   6.071765   
1147     1.0       1.0  49.0  49.0  49.0  49.0  45.0  37.0  63.197145   
1148     1.0       0.0  49.0  48.0  48.0  45.0  43.0  33.0  30.461898   
1149     1.0       1.0  39.0  36.0  29.0  23.0  13.0   7.0  40.525739   
1150     1.0       1.0   7.0   7.0   7.0   7.0   7.0   5.0  69.423565   

       exudate9  exudate10 exudate11 exudate12 exudate13 exudate14 exudate15  \
0     17.775994   5.270920  0.771761  0.018632  0.006864  0.003923  0.003923   
1     23.799994   3.325423  0.234185  0.003903  0.003903  0.003903  0.003903   
2     27.993933  12.687485  4.852282  1.393889  0.373252  0.041817  0.007744   
3     18.445954   9.118901  3.079428  0.840261  0.272434  0.007653  0.001531   
4      8.570709   0.410381  0.000000  0.000000  0.000000  0.000000  0.000000   
...         ...        ...       ...       ...       ...       ...       ...   
1146   0.937472   0.031145  0.003115  0.000000  0.000000  0.000000  0.000000   
1147  27.377668   8.067688  0.979548  0.001552  0.000000  0.000000  0.000000   
1148  13.966980   1.763305  0.137858  0.011221  0.000000  0.000000  0.000000   
1149  12.604947   4.740919  1.077570  0.563518  0.326860  0.239568  0.174584   
1150   7.031843   1.750548  0.046597  0.021180  0.008472  0.000000  0.000000   

        euDist  diameter amfm_class label  
0     0.486903  0.100025        1.0  b'0'  
1     0.520908  0.144414        0.0  b'0'  
2     0.530904  0.128548        0.0  b'1'  
3     0.483284  0.114790        0.0  b'0'  
4     0.475935  0.123572        0.0  b'1'  
...        ...       ...        ...   ...  
1146  0.537470  0.116795        0.0  b'0'  
1147  0.516733  0.124190        0.0  b'0'  
1148  0.560632  0.129843        0.0  b'0'  
1149  0.485972  0.106690        1.0  b'1'  
1150  0.556192  0.088957        0.0  b'0'  

[1151 rows x 20 columns]

In [290]:
X = df.drop(columns=['label'])
X

quality prescreen   ma2   ma3   ma4   ma5   ma6   ma7   exudate8  \
0        1.0       1.0  22.0  22.0  22.0  19.0  18.0  14.0  49.895756   
1        1.0       1.0  24.0  24.0  22.0  18.0  16.0  13.0  57.709936   
2        1.0       1.0  62.0  60.0  59.0  54.0  47.0  33.0  55.831441   
3        1.0       1.0  55.0  53.0  53.0  50.0  43.0  31.0  40.467228   
4        1.0       1.0  44.0  44.0  44.0  41.0  39.0  27.0  18.026254   
...      ...       ...   ...   ...   ...   ...   ...   ...        ...   
1146     1.0       1.0  34.0  34.0  34.0  33.0  31.0  24.0   6.071765   
1147     1.0       1.0  49.0  49.0  49.0  49.0  45.0  37.0  63.197145   
1148     1.0       0.0  49.0  48.0  48.0  45.0  43.0  33.0  30.461898   
1149     1.0       1.0  39.0  36.0  29.0  23.0  13.0   7.0  40.525739   
1150     1.0       1.0   7.0   7.0   7.0   7.0   7.0   5.0  69.423565   

       exudate9  exudate10 exudate11 exudate12 exudate13 exudate14 exudate15  \
0     17.775994   5.270920  0.771761  0.018632  0.006864  0.003923  0.003923   
1     23.799994   3.325423  0.234185  0.003903  0.003903  0.003903  0.003903   
2     27.993933  12.687485  4.852282  1.393889  0.373252  0.041817  0.007744   
3     18.445954   9.118901  3.079428  0.840261  0.272434  0.007653  0.001531   
4      8.570709   0.410381  0.000000  0.000000  0.000000  0.000000  0.000000   
...         ...        ...       ...       ...       ...       ...       ...   
1146   0.937472   0.031145  0.003115  0.000000  0.000000  0.000000  0.000000   
1147  27.377668   8.067688  0.979548  0.001552  0.000000  0.000000  0.000000   
1148  13.966980   1.763305  0.137858  0.011221  0.000000  0.000000  0.000000   
1149  12.604947   4.740919  1.077570  0.563518  0.326860  0.239568  0.174584   
1150   7.031843   1.750548  0.046597  0.021180  0.008472  0.000000  0.000000   

        euDist  diameter amfm_class  
0     0.486903  0.100025        1.0  
1     0.520908  0.144414        0.0  
2     0.530904  0.128548        0.0  
3     0.483284  0.114790        0.0  
4     0.475935  0.123572        0.0  
...        ...       ...        ...  
1146  0.537470  0.116795        0.0  
1147  0.516733  0.124190        0.0  
1148  0.560632  0.129843        0.0  
1149  0.485972  0.106690        1.0  
1150  0.556192  0.088957        0.0  

[1151 rows x 19 columns]

## Rumus prepocessing data Min Max

$$
\displaystyle x = \frac{x_{i} - x_{min}}{x_{max} - x_{min}}
$$

In [291]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
#scaler.fit(features)
#scaler.transform(features)
scaled = scaler.fit_transform(X)
features_names = X.columns.copy()
#features_names.remove('label')
scaled_features = pd.DataFrame(scaled, columns=features_names)
scaled_features.head(10)

quality prescreen       ma2       ma3       ma4       ma5       ma6  \
0     1.0       1.0  0.140000  0.160305  0.176471  0.173077  0.177083   
1     1.0       1.0  0.153333  0.175573  0.176471  0.163462  0.156250   
2     1.0       1.0  0.406667  0.450382  0.487395  0.509615  0.479167   
3     1.0       1.0  0.360000  0.396947  0.436975  0.471154  0.437500   
4     1.0       1.0  0.286667  0.328244  0.361345  0.384615  0.395833   
5     1.0       1.0  0.286667  0.320611  0.336134  0.384615  0.375000   
6     1.0       0.0  0.186667  0.213740  0.235294  0.250000  0.250000   
7     1.0       1.0  0.033333  0.038168  0.042017  0.048077  0.010417   
8     1.0       1.0  0.140000  0.152672  0.142857  0.134615  0.125000   
9     1.0       1.0  0.520000  0.564885  0.605042  0.673077  0.656250   

        ma7  exudate8  exudate9 exudate10 exudate11 exudate12 exudate13  \
0  0.147727  0.122764  0.106359  0.049693  0.012913  0.000362  0.000342   
1  0.136364  0.142126  0.142403  0.031351  0.003918  0.000076  0.000194   
2  0.363636  0.137472  0.167497  0.119614  0.081188  0.027106  0.018571   
3  0.340909  0.099403  0.110368  0.085971  0.051525  0.016340  0.013555   
4  0.295455  0.043799  0.051281  0.003869  0.000000  0.000000  0.000000   
5  0.318182  0.069395  0.041498  0.021738  0.005417  0.000000  0.000000   
6  0.170455  0.037412  0.054531  0.015400  0.000000  0.000000  0.000000   
7  0.000000  0.050374  0.056828  0.011536  0.002516  0.000000  0.000000   
8  0.102273  0.164381  0.140880  0.057991  0.008305  0.000000  0.000000   
9  0.522727  0.053997  0.060159  0.008246  0.001670  0.000455  0.000000   

  exudate14 exudate15    euDist  diameter amfm_class  
0  0.000661  0.001271  0.530801  0.261133        1.0  
1  0.000657  0.001264  0.682302  0.536341        0.0  
2  0.007043  0.002509  0.726836  0.437973        0.0  
3  0.001289  0.000496  0.514678  0.352675        0.0  
4  0.000000  0.000000  0.481936  0.407122        0.0  
5  0.000000  0.000000  0.601764  0.426770        0.0  
6  0.000000  0.000000  0.775126  0.506339        0.0  
7  0.000000  0.000000  0.929166  0.081622        1.0  
8  0.000000  0.000000  0.589477  0.365093        0.0  
9  0.000000  0.000000  0.860738  0.317608        0.0

## Save model prepocessing

In [292]:
import joblib
filename = "norm.sav"
joblib.dump(scaler, filename) 

['norm.sav']

In [293]:
y = df['label'].values

## Encoder Label

In [294]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
y_baru = le.fit_transform(y)
y_baru

array([0, 0, 1, ..., 0, 1, 0])

## Split dataset

In [295]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y_baru, test_size=0.2, random_state=1)

## Inisialisasi model knn 



### Tanpa data Normalisasi

In [296]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

my_param_grid = {'n_neighbors':[2,3,5,7], 'weights': ['distance', 'uniform']}
modelKNN = GridSearchCV(KNeighborsClassifier(), param_grid=my_param_grid, refit=True, verbose=3, cv=3)

In [297]:
# my_param_grid = {'n_neighbors':[2,3,5,7], 'weights': ['distance', 'uniform']}
# GridSearchCV(estimator=KNeighborsClassifier(), param_grid=my_param_grid, refit=True, verbose=3, cv=3)
# knn = GridSearchCV(KNeighborsClassifier(), param_grid=my_param_grid, refit=True, verbose=3, cv=3)

In [298]:
modelKNN.fit(X_train, y_train)

Fitting 3 folds for each of 8 candidates, totalling 24 fits
[CV 1/3] END ...n_neighbors=2, weights=distance;, score=0.609 total time=   0.0s
[CV 2/3] END ...n_neighbors=2, weights=distance;, score=0.609 total time=   0.0s
[CV 3/3] END ...n_neighbors=2, weights=distance;, score=0.601 total time=   0.0s
[CV 1/3] END ....n_neighbors=2, weights=uniform;, score=0.638 total time=   0.0s
[CV 2/3] END ....n_neighbors=2, weights=uniform;, score=0.619 total time=   0.0s
[CV 3/3] END ....n_neighbors=2, weights=uniform;, score=0.621 total time=   0.0s
[CV 1/3] END ...n_neighbors=3, weights=distance;, score=0.638 total time=   0.0s
[CV 2/3] END ...n_neighbors=3, weights=distance;, score=0.629 total time=   0.0s
[CV 3/3] END ...n_neighbors=3, weights=distance;, score=0.624 total time=   0.0s
[CV 1/3] END ....n_neighbors=3, weights=uniform;, score=0.632 total time=   0.0s
[CV 2/3] END ....n_neighbors=3, weights=uniform;, score=0.625 total time=   0.0s
[CV 3/3] END ....n_neighbors=3, weights=uniform;,

GridSearchCV(cv=3, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [2, 3, 5, 7],
                         'weights': ['distance', 'uniform']},
             verbose=3)

### Save Model K-NN Tanpa Normalisasi

In [299]:
filenameModel = 'modelKnn.pkl'
joblib.dump(modelKNN, filenameModel)

['modelKnn.pkl']

In [300]:
test_pred = modelKNN.predict(X_test)

In [301]:
test_pred

array([1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1])

In [302]:
from sklearn.metrics import accuracy_score
print(f'accuracy = {(accuracy_score(y_test, test_pred))*100}%')

accuracy = 63.63636363636363%


In [303]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(scaled_features, y_baru, test_size=0.2, random_state=1) 

In [304]:
my_param_grid = {'n_neighbors':[2,3,5,7], 'weights': ['distance', 'uniform']}
GridSearchCV(estimator=KNeighborsClassifier(), param_grid=my_param_grid, refit=True, verbose=3, cv=3)
knn = GridSearchCV(KNeighborsClassifier(), param_grid=my_param_grid, refit=True, verbose=3, cv=3)

In [305]:
knn.fit(X_train, y_train)

Fitting 3 folds for each of 8 candidates, totalling 24 fits
[CV 1/3] END ...n_neighbors=2, weights=distance;, score=0.612 total time=   0.0s
[CV 2/3] END ...n_neighbors=2, weights=distance;, score=0.560 total time=   0.0s
[CV 3/3] END ...n_neighbors=2, weights=distance;, score=0.575 total time=   0.0s
[CV 1/3] END ....n_neighbors=2, weights=uniform;, score=0.599 total time=   0.0s
[CV 2/3] END ....n_neighbors=2, weights=uniform;, score=0.612 total time=   0.0s
[CV 3/3] END ....n_neighbors=2, weights=uniform;, score=0.569 total time=   0.0s
[CV 1/3] END ...n_neighbors=3, weights=distance;, score=0.606 total time=   0.0s
[CV 2/3] END ...n_neighbors=3, weights=distance;, score=0.573 total time=   0.0s
[CV 3/3] END ...n_neighbors=3, weights=distance;, score=0.605 total time=   0.0s
[CV 1/3] END ....n_neighbors=3, weights=uniform;, score=0.599 total time=   0.0s
[CV 2/3] END ....n_neighbors=3, weights=uniform;, score=0.567 total time=   0.0s
[CV 3/3] END ....n_neighbors=3, weights=uniform;,

GridSearchCV(cv=3, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [2, 3, 5, 7],
                         'weights': ['distance', 'uniform']},
             verbose=3)

### Save Model K-NN Normalisasi

In [306]:
filenameModelKnnNorm = 'modelKnnNorm.pkl'
joblib.dump(knn, filenameModelKnnNorm)

['modelKnnNorm.pkl']

In [307]:
pred_test = knn.predict(X_test)

In [308]:
print(f'acuracy = {accuracy_score(y_test, pred_test) * 100 :.2f}')

acuracy = 63.64


In [309]:
# training the model on training set
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB()

In [310]:
filenameModelGau = 'modelGau.pkl'
joblib.dump(gnb, filenameModelGau)

['modelGau.pkl']

In [311]:
# making predictions on the testing set
y_pred = gnb.predict(X_test)

In [312]:
y_pred

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1])

In [313]:
print(f'acuracy = {accuracy_score(y_test, y_pred)}')

acuracy = 0.6320346320346321


## Predict Input

In [314]:
# a = []
# a.append('1.0	1.0	5.0	5.0	5.0	5.0	4.0	3.0	133.054234	6.890885	2.718365	0.169898	0.01794	0.011608	0.003166	0.001055	0.588627	0.109748	1.0'.split())
# a.append('1.0	1.0	22.0	22.0	22.0	19.0	18.0	14.0	49.895756	17.775994	5.27092	0.771761	0.018632	0.006864	0.003923	0.003923	0.486903	0.100025	1.0'.split())
a = np.array(df.iloc[:10,:-1])
test_data = np.array(a).reshape(10,-1)
test_data.shape

(10, 19)

### Load Model Normalisasi

In [315]:
scaler = joblib.load(filename)
test_d = scaler.fit_transform(test_data)
pd.DataFrame(test_d)

0    1         2         3         4         5         6         7   \
0  0.0  1.0  0.219178  0.231884  0.238806  0.200000  0.258065  0.282609   
1  0.0  1.0  0.246575  0.260870  0.238806  0.184615  0.225806  0.260870   
2  0.0  1.0  0.767123  0.782609  0.791045  0.738462  0.725806  0.695652   
3  0.0  1.0  0.671233  0.681159  0.701493  0.676923  0.661290  0.652174   
4  0.0  1.0  0.520548  0.550725  0.567164  0.538462  0.596774  0.565217   
5  0.0  1.0  0.520548  0.536232  0.522388  0.538462  0.564516  0.608696   
6  0.0  0.0  0.315068  0.333333  0.343284  0.323077  0.370968  0.326087   
7  0.0  1.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
8  0.0  1.0  0.219178  0.217391  0.179104  0.138462  0.177419  0.195652   
9  0.0  1.0  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   

         8         9         10        11        12        13        14  \
0  0.672228  0.514778  0.395903  0.159051  0.013367  0.018390  0.093814   
1  0.824719  0.800841  0.237437  0.048263  0.002800  0.010457  0.093335   
2  0.788061  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
3  0.488234  0.546593  0.709330  0.634635  0.602818  0.729893  0.183012   
4  0.050306  0.077645  0.000000  0.000000  0.000000  0.000000  0.000000   
5  0.251895  0.000000  0.154384  0.066716  0.000000  0.000000  0.000000   
6  0.000000  0.103436  0.099625  0.000000  0.000000  0.000000  0.000000   
7  0.102086  0.121669  0.066244  0.030992  0.000000  0.000000  0.000000   
8  1.000000  0.788758  0.467597  0.102297  0.000000  0.000000  0.000000   
9  0.130619  0.148101  0.037814  0.020564  0.016778  0.000000  0.000000   

         15        16        17   18  
0  0.506586  0.109262  0.394775  1.0  
1  0.504003  0.448014  1.000000  0.0  
2  1.000000  0.547593  0.783674  0.0  
3  0.197701  0.073210  0.596090  0.0  
4  0.000000  0.000000  0.715828  0.0  
5  0.000000  0.267934  0.759036  0.0  
6  0.000000  0.655569  0.934022  0.0  
7  0.000000  1.000000  0.000000  1.0  
8  0.000000  0.240459  0.623400  0.0  
9  0.000000  0.846996  0.518972  0.0

### Load Model KNN

In [316]:
knn = joblib.load(filenameModelKnnNorm)

In [317]:
inp_pred = knn.predict(test_d)
inp_pred

array([0, 1, 1, 1, 1, 1, 1, 0, 1, 1])

### Load Model Gausian

In [318]:
gnb = joblib.load(filenameModelGau)

In [319]:
inp_pred = gnb.predict(test_d)
inp_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])